name: Run Playwright Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  playwright-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-playwright-tests .

      - name: Run tests inside Docker
        run: docker run --rm my-playwright-tests
